// <auto-generated />
using System;
using FilmDiziSitesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmDiziSitesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FilmDiziSitesi.Models.MovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfişUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Açıklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bütçe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FragmanUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiseHasilati")
                        .HasColumnType("TEXT");

                    b.Property<int>("IzlenmeSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oyuncular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Puan")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("Süre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tür")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VizyonTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yönetmen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ülke")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("FilmDiziSitesi.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
